### ISSUE TITLE
2.1 CloudArchitectBasic 슬라이드 수정

### ISSUE THREAD

**Issue by unhochoi** [ddps-lab/architect-cloud#12]

**Comment by subeans** [comment]
https://docs.google.com/presentation/d/1hxyc7o8pHmJyYCErgIewaNEwRAIiDkV5_pDIBxybFO4/edit?usp=sharing
2.1 슬라이드를 사본을 만들어서 [수정 검토]2.1MultiAZSubnet슬라이드 로 수정해보았습니다.

변경된 사항
1. 캡쳐 화면 ( 부분화면 -> 전체화면 )
캡쳐 부분이 어느 부분인지 직관적으로 알기 힘든 부분도 있는 것 같아서 최대한 사용자가 보는 화면과 같은 전체 페이지를 캡쳐하는 방식으로 진행했는데 이에 따른 단점도 있습니다. (  글자가 너무 작습니다. 개인적으로 pdf를 받아서 실행할 수 있는 환경(확대가능)인지 아니면 교수님께서 앞에 띄워두고 진행하는 방식인지에 따라 수정이 필요할 것 같습니다.  )
2. 사용자가 직접 클릭해야하는 부분이나 입력해야하는 부분은 [ ] 대괄호로 표시했습니다.
3. 사용자가 진행해야하는 순서에 대해서 표시 추가했습니다.
4. 사용자가 진행해야 하는 부분이 아닌 결과를 보는 부분의 박스는 파란색으로 표시하여 실행행야하는 부분, 아닌 부분을 조금 더 직관적으로 구분하였습니다.

글씨가 작은 부분에 대해 부분 화면으로 캡쳐를 진행할지, 전체 화면으로 진행할지 의견이 필요합니다.

**Comment by kmu-leeky** [comment]
응 수빈아 잘 봤다. 지금 해둔것도 괜찮은것 같아. 실제로 수업에서 실습 진행할때는 내가 슬라이드 보고 이것저것 해보세요 하고 시간을 조금 주거든. 그래서 지금 수빈이가 만들어준 형태도 괜찮아보인다. 작업할때 상황봐가면서 zoom in, out 적절히 섞어서 해보자.
