### ISSUE TITLE
슬라이드 별 명령어들을 슬라이드 번호 기준으로 작성하여, README.md 또는 txt 파일로 제공하는 방식도 괜찮을 듯 함

### ISSUE THREAD

**Issue by unhochoi** [ddps-lab/architect-cloud#18]

**Comment by kmu-leeky** [comment]
이렇게 제공을 했을때 슬라이드 작성할때 copy-paste 문제를 해결 할 수도 있다면 유용할것 같아. 윈도우에서 copy-paste 문제를 덜 신경써도 괜찮고

**Comment by unhochoi** [comment]
https://github.com/ddps-lab/architect-cloud/blob/master/sample-application/README.md
상단 링크로 제공할 예정
