### ISSUE TITLE
실습 : CI/CD(커피 공급업체 리스팅) 오토스케일링 시나리오 추가

### ISSUE THREAD

**Issue by red0sena** [ddps-lab/architect-cloud#25]
기존 커피 공급업체 리스팅 실습에 고가용성 및 확장성 구현 시나리오를 추가합니다.
-  Application Load Balancer 생성
-  Amazon EC2 Auto Scaling 구현
- 애플리케이션 로드 테스트
- 프론트에 인스턴스 메타데이터 표시

**Comment by red0sena** [comment]
## 커피 공급업체 리스팅 실습에 고가용성 및 확장성 구현 시나리오

### ALB연결
- ALB연결
- ALB


### Locus를 이용한 로드 테스트 진행
<img width="1017" alt="Screenshot 2024-04-07 at 21 53 16" src="https://github.com/ddps-lab/architect-cloud/assets/106056971/7ed1b444-43c1-4765-ad14-28a81aab9d85">


<img width="1631" alt="Screenshot 2024-04-07 at 21 53 11" src="https://github.com/ddps-lab/architect-cloud/assets/106056971/84673210-3e84-4960-9cae-479afbc1e620">


<img width="574" alt="Screenshot 2024-04-07 at 21 57 15" src="https://github.com/ddps-lab/architect-cloud/assets/106056971/4c7a06e7-d1d8-446a-b65f-9ff1754ba37a">

**Comment by red0sena** [comment]
## 모놀로식 인스턴스 오토스케일링 시나리오 실행

- 실습계정에서 모놀로식 인스턴스 오토스케일링을 실행하였습니다. 아래 노션 링크에 전체 진행을 정리하였습니다.
https://mighty-almanac-36a.notion.site/39afb6a0499641779886781ac089c6dd?pvs=4


- 기존 실습 모듈에 CloudFormation YAML 파일이 있어 해당 파일을 이용해 쉽게 앱 인스턴스와 RDS를 생성할 수 있었고 ALB와 AutoScaling만 추가하였습니다.
- locust를 이용하여 요청수를 늘려 스케일링을 진행하였고 아래와 같은 결과를 얻을 수 있었습니다.
 
**locust실행 전 하나의 앱만 실행되는 모습**
<img width="1677" alt="Untitled" src="https://github.com/ddps-lab/architect-cloud/assets/106056971/29e7e622-4e91-43c8-a823-34e4227010dd">

**locust실행 후 3개까지 스케일링 된 모습**
<img width="1682" alt="Untitled2" src="https://github.com/ddps-lab/architect-cloud/assets/106056971/ab3b90d6-1dc7-4395-9a05-e6fbf1823219">
<img width="1706" alt="Untitled3" src="https://github.com/ddps-lab/architect-cloud/assets/106056971/10618907-3ec9-4c10-adb4-a48d4cf2f634">

**Comment by kmu-leeky** [comment]
경환아. 이 이슈에서 확인하는 내용이 커피 시나리오 모노리스 환경이 auto-scaling 되는지 보는거지? EC2 인스턴스로 스케일링 인거지? 컨테이너 기반이 아니라. 이 내용은 완료가 되었다고 볼 수 있을까? 정상적으로 잘 동작하는거고?

지난주 금요일 회의때 각자 확인할 내용을 하나씩 정했던것 같은데, 어떤것이었는지 확인해주면서 이슈를 각자 만들도록 하자 @mumat0103 @kh3654po  확인 부탁.

**Comment by red0sena** [comment]
네 커피 시나리오 모노리스 환경의 auto-scaling을 확인하는 내용입니다. 
시나리오가 정상적으로 잘 작동함을 확인하였습니다.
