### ISSUE TITLE
삼성 클라우드 수강생 계정 생성 및 헬퍼 계정 생성

### ISSUE THREAD

**Issue by mumat0103** [ddps-lab/architect-cloud#26]
https://github.com/kmu-leeky/cloud-util/blob/master/create_account_link.py 를 통해 계정을 생성하고 권한 부여를 합니다.

`def create_account(start=0, end=0, alias=""):` 에 start는 `2024001`, end는 `2024100`로 지정하여 계정 100개를 생성합니다.
수업 수강생들은 1번 계정부터 사용하고 헬퍼는 100번부터 앞으로 가면서 계정을 사용합니다.

수강생들이 문제가 생기면 `def create_signin_links (email_to_id, policy=root_policy, duration = 43200):`를 사용해서 수강생 계정에 접근할 수 있는 링크를 생성합니다.

**Comment by red0sena** [comment]
계정은 cloud-architect+@kookmin.ac.kr로 생성 완료하여 수강생 계정에 접근할 수 있는 링크를 생성하는 단계로 넘어가면 될 것 같습니다.

**Comment by red0sena** [comment]
슬랙 github 연동 이슈 테스트

**Comment by red0sena** [comment]
슬랙 github 연동 이슈 테스트

**Comment by mumat0103** [comment]
터미널에서 python3 을 입력하여 파이썬을 켭니다.

파이썬에서 `import create_account_link as cal` 을 입력하여 계정 생성 모듈을 불러옵니다.

그런 다음에 `cal.get_signin_link("100")` 을 입력하면 지정한 유저 계정에 접근할 수 있는 링크가 생성됩니다.
![image](https://github.com/ddps-lab/architect-cloud/assets/69793985/5f541377-6424-4e3b-959a-6e06c55dd40f)
콘솔화면

![image](https://github.com/ddps-lab/architect-cloud/assets/69793985/1359b29f-9f22-484c-91c1-c0c45ac4a472)
로그인이 완료된 화면

**Comment by kmu-leeky** [comment]
오케이 잘 정리했다. 무리없이 동작하는것 같아 다행이다. 이번에 계정 생성한 명령어및 차례, 주의점, 그리고 계정 링크 생성하는걸 설명하는 문서를 하나 만들어줄래?
지금 공유된 구글 독스에 추가로 작성해줘도 좋을것 같아.

**Comment by mumat0103** [comment]
계정 링크 생성은 [구글독스](https://docs.google.com/document/d/164LQEvNnKpIjHjDoDvOEimIbu60RBdAz6qUN3IbZf18/edit?usp=drive_link) 하단에 2024 삼성 클라우드 아키텍처로 구분해서 추가하였습니다.

계정 생성 부분은 제가 진행하지 않아 경환님이 작성하기로 했습니다.

**Comment by mumat0103** [comment]
계정 생성 및 계정 링크 확인 완료하였으므로 Close 하겠습니다.
