### ISSUE TITLE
커피 공급 시나리오에 메타데이터 추가

### ISSUE THREAD

**Issue by mumat0103** [ddps-lab/architect-cloud#27]
커피 공급 시나리오에 메타데이터를 추가합니다.

**Comment by mumat0103** [comment]
![image](https://github.com/ddps-lab/architect-cloud/assets/69793985/c8d2b803-7fe5-4cd0-bdd0-ef52c6301b22)
customer 화면
![image](https://github.com/ddps-lab/architect-cloud/assets/69793985/2fd9c5cf-553a-4a92-b647-8ece4c89bba9)
employee 화면

customer와 employee 페이지에 메타데이터 추가 완료하였습니다.
로드밸런서 붙여서 요청이 분리되어 갔을 때, 메타데이터가 변하는지 확인해보겠습니다.

**Comment by kmu-leeky** [comment]
오케이. 잘 했다. 로드밸런서 하는 것도 할줄 알아야 하니 이번에 다 한번 해보자.

**Comment by mumat0103** [comment]
모놀리딕 환경에서 로드밸런서 붙여서 테스트까지 완료하였습니다. 더 세세한 부분은 진행하면서 수정하면 될 것 같습니다.


![image](https://github.com/ddps-lab/architect-cloud/assets/69793985/d3f05415-588f-4f3e-b163-59515c61a385)
35.85.39.32 - csk-monoTest


![image](https://github.com/ddps-lab/architect-cloud/assets/69793985/348cf02b-6789-47cb-a9b7-0d7ebaccda90)
같은 alb 주소로 접근 했을 때, 메타데이터가 정상적으로 변하는 것을 확인 (ALB 생성 시 생긴 인스턴스)

![image](https://github.com/ddps-lab/architect-cloud/assets/69793985/1023874a-667b-4307-a2c1-1692092c57ab)
부하 테스트 했을 때 2개 인스턴스가 새로 생기는 것을 확인


![image](https://github.com/ddps-lab/architect-cloud/assets/69793985/e5efa33b-bf92-4a82-a293-cf99b38d33de)
![image](https://github.com/ddps-lab/architect-cloud/assets/69793985/18634e25-55b0-4b60-8f7f-20efc3b4dca1)

오토 스케일링으로 새로 생긴 인스턴스에 접근하여 메타데이터가 출력되는 모습

**Comment by kmu-leeky** [comment]
오케이. 잘 확인했다. 해당 내용으로 진행해보자.

**Comment by mumat0103** [comment]
완료하였으므로 Close 하겠습니다.
