### ISSUE TITLE
CI/CD(커피 공급업체 리스팅) 컨테이너 오토스케일링 시나리오

### ISSUE THREAD

**Issue by kh3654po** [ddps-lab/architect-cloud#28]
커피 시나리오 컨테이너 환경의 auto-scaling 시나리오 작성

**Comment by kmu-leeky** [comment]
경환이는 모노리스 환경에서 ec2 인스턴스의 오토 스케일링을 석현이는 컨테이너의 auto scaling 을 수행한다는 이야기인거지?

**Comment by kh3654po** [comment]
네 맞습니다. 교수님 그리고 실습을 했는데 알고보니 하나 더 있는것을 이제 알았습니다. ci/cd 과목도 초대해주실수 있나요?

**Comment by kmu-leeky** [comment]
초대 메시지가 안갔으려나. 지금 다시 보내기를 했으니 확인해줘.
강의 링크는 여기 - https://awsacademy.instructure.com/courses/78783

**Comment by kh3654po** [comment]
감사합니다

**Comment by kh3654po** [comment]
microservice 배포까지 진행완료했습니다. 실습 진행중 실수를 너무 많이해서 완료하는데 너무 오래걸렸습니다. 실습진행은 완료되었고 오토스케일링까지 진행 후 경환님이 진행하신대로 가상 유저들로 과부하 시킨후 오토스케일링이 잘진행되는지까지 확인하겠습니다.

**Comment by kmu-leeky** [comment]
오케이. 그래 보자. 실수 한 내용에 유념해서 실습 슬라이드를 만들어보자.

**Comment by kh3654po** [comment]
삼성 강의때 사용 할 계정에서 ecr, ecs, awscommit, awspipeline, cloud9, awsdeploy 등의 서비스를 사용하여 커피 마이크로서비스 실습을 진행했습니다. 실습 막힘없이 잘진행됐고 거기에 오토스케일링까지 확인했습니다.

마이크로 서비스로 구축할 때 customer와 employee로 나누었습니다.

ecs 서비스에서 오토스케일링 기능을 제공하여 아래와 같이 태스크를 최소 1개 최대 3개로 설정하고 request가 10개가 넘어갈 때 확장하도록 설정하였습니다. 이는 customer에 대한 설정입니다.
![image](https://github.com/ddps-lab/architect-cloud/assets/54831356/fe892210-7c9f-4b53-b09a-b59f886539ca)

locust 툴을 사용해 더미 유저로 customer에 초당 500개의 요청을 지속적으로 보냈습니다.
![image](https://github.com/ddps-lab/architect-cloud/assets/54831356/d2c3c561-5f00-43bf-a0d8-dd9b7aa1890b)

customer ecs 서비스에서 기존 1개의 태스크에서 3개로 확장된것을 확인했습니다.
![image](https://github.com/ddps-lab/architect-cloud/assets/54831356/ccf96015-1f0f-497c-a2bd-c3dbe792bea5)

**Comment by kh3654po** [comment]
추가적으로 요청을 중지후 8분뒤에 태스크 하나가 줄었고 축소 휴지 기간인 180초가 지난 후 1개가 더 줄어든것도 확인했습니다.

<img width="1072" alt="image" src="https://github.com/ddps-lab/architect-cloud/assets/54831356/c453d2c9-866c-41f3-83dc-2dbe8089155b">
<img width="1080" alt="image" src="https://github.com/ddps-lab/architect-cloud/assets/54831356/eb4891ac-9092-4af0-8122-17bc4cce9b1c">

**Comment by kmu-leeky** [comment]
오케이. 잘했다 석현아. 그렇다면 해당 내용은 무리없이 동작하는걸로 파악하고 있을께.

**Comment by kh3654po** [comment]
넵!

**Comment by kmu-leeky** [comment]
석현아. 실습을 했던 내용이 2022년도에 강의했던 슬라이드에서 작업한 ECS 내용과 얼마나 유사한지 한번 봐볼래? 22년도에는 VPC 설정부터 해서 기본적인걸 다했는데, 석현이 실습에서는 어떻게 했는지 궁금 함.

https://docs.google.com/presentation/d/1CytW28r47ZHksRlhIT67wFO7E8HwmghePob1wtyMnFY/edit?usp=sharing
