### ISSUE TITLE
Serverless 시나리오에서, EFS 대신 ECR Image 를 사용하는 방식 추가

### ISSUE THREAD

**Issue by unhochoi** [ddps-lab/architect-cloud#3]
Container 시나리오에서 사용된 Image 와 동일한 Image 를 사용할 수 있다면 Best
만약, 동일한 Image 를 사용할 수 없다면, 각자 다른 Image 를 사용

**Comment by kmu-leeky** [comment]
EFS 시나리오가 복잡한듯 함 (테스트 삼아 남겨보는 코멘트)

**Comment by kmu-leeky** [comment]
업데이트 공지 - /github subscribe ddps-lab/architect-cloud comments

**Comment by unhochoi** [comment]
- Container 시나리오 Image 와 Serverless 시나리오 Image 를 동일하게 사용하는 것은 어려워보임
    - Base Image 차이, Lambda Handler 호출 차이 등
- 따라서, 각자 다른 Image 를 사용할 계획

**Comment by kmu-leeky** [comment]
오케이. 그러면 별도의 컨테이너 이미지를 생성하도록 준비를 하자. ecr 에 업로드 할때 이미지 명에 ecs, lambda 정도의 접미사를 붙여서 알아보기 쉽게 하는것도 좋을것 같아. 작년에 사용한 efs 사용하는 슬라이드는 참고용으로 제공해줄수 있게끔 삭제하지는 말고 일단은 남겨두도록 하자.

**Comment by unhochoi** [comment]
EFS 시나리오에 해당하는 슬라이드를 분리해 별도로 저장해놓는 걸 말씀하시는걸까요? 
아니면 기존 슬라이드에 두 가지 시나리오를 모두 설명하는 방식을 말씀하시는걸까요?

**Comment by kmu-leeky** [comment]
내용 구성은 내가 조금 더 고민해볼께. 우선은 슬라이드만 그자리에 그대로 두고 이미지로 하는걸 추가해보자. 어떻게 진행하는게 좋을런지 생각해보고 구성해볼께.

**Comment by kmu-leeky** [comment]
efs 내용에 대한건 굳이 새롭게 작업할 필요는 없고, 그냥 작년 내용을 지우지만 말고 놔두면 될것 같아.

**Comment by unhochoi** [comment]
넵, 알겠습니다.
