### ISSUE TITLE
01. CloudArchitectBasic VPC, EC2 생성 시나리오에서, 인스턴스 정보 가져오지 못하는 에러 발생

### ISSUE THREAD

**Issue by jaeriver** [ddps-lab/architect-cloud#5]
그림에 빨간 박스 부분이 현재 이슈입니다. 코드상에서 인스턴스에 대한 정보를 가져오지 못하여 Error로 뜨는 상황입니다.
![Image](https://user-images.githubusercontent.com/28581495/166204890-e17bd8c6-bc5f-4756-8bb3-b934b826742b.png)

해당 부분 코드는 다음과 같습니다.
![Image](https://user-images.githubusercontent.com/28581495/166205163-bc1c8cb7-74ac-40f1-b101-f0059bcbfb72.png)
빨간박스 부분에서 현재 json data가 response로 오는 것이 아닌 빈값이 오는 상황이여 에러가 발생합니다.

**Comment by hyoonseo159357** [comment]
![Image](https://user-images.githubusercontent.com/50091802/166208196-356b423c-967a-41db-b9ad-2e9ba6e9f29d.png)



![Image](https://user-images.githubusercontent.com/50091802/166206255-5ca22f7b-6821-4b40-b8c1-0f3570495b96.png)

https://freegeoip.app/json 해당 사이트가 접속이 막혀서 다른 사이트를 사용해서 진행해주었습니다.

1. http://ipapi.co/json 에서 ip,country_name,region,latitude,longitude를 불러오고
2. http://ipinfo.io/json 에서 timezone를 불러왔습니다.
3. 또, 기존의 region_name -> region으로 ,time_zone -> timezone 으로 바꿔주었습니다.

**Comment by kmu-leeky** [comment]
오케이. 이전에 @hyoonseo159357 가 만든 커밋에서 해결이 된것같네. 그렇다면 이 이슈에다가 어떤 커밋이 이번 이슈와 연관 있는지 링크를 남긴 후에 close 하는게 맞겠다.

**Comment by kmu-leeky** [comment]
에러는 어떻게 발생하게해서 진행을 했어?

**Comment by jaeriver** [comment]
단순히 web 을 열어둔 ec2에 접속하여 무한으로 request를 보냈습니다.
처음에는 200 response가 왔으나 요청량이 많아지면서 429 error response를 확인했습니다.

import requests

while(True):
        requests.get('http://ipapi.co/json')

**Comment by kmu-leeky** [comment]
웹과 별도의 서비스에서 지속적으로 요청을 보내는 상황에서 에러가 발생하기 시작했을때 웹에서 확인을 해본거네?
그런데 요청을 보낸곳이
http://ipinfo.io/json
http://ipapi.co/json

두군데가 서로 다른것 같은데 둘다 에러가 나오는거야?

**Comment by jaeriver** [comment]
넵 두군데 모두 요청량을 늘렸을 때 429 에러가 발생했습니다.

**Comment by hyoonseo159357** [comment]
둘다 모두 에러429 났을때를 확인해보았습니다. 위에 재강님이 말씀해주신것처럼 동일하게 진행해주었습니다.
<img width="1607" alt="image" src="https://user-images.githubusercontent.com/50091802/168785297-1bd70c18-31bb-4048-a222-4874b012d04a.png">

**Comment by kmu-leeky** [comment]
만약에 한곳만 늘리면 어떻게 될까?
그리고 내일 컨테이너 내용을 다루는데 이게 확실히 제대로 적용이 되겠지? 오늘 같은 문제가 발생하지 않고?

**Comment by unhochoi** [comment]
dockerfile 내부에서도 flask-inference 의 main.py 를 사용하기 때문에, 문제가 없을 것으로 보이나 한 번 실행해보겠습니다.

**Comment by jaeriver** [comment]
한 곳만 늘린 결과는 위에 운호가 진행한 3가지 case에서 보실 수 있습니다. 결과적으로 문제는 없습니다.

**Comment by hyoonseo159357** [comment]
2개 실험을 진행하고 api 2개중에 한개만 에러를 발생시켰을때, 이전에 이미 2개 api로429 에러가 발생하여 일정 시간동안은 error 메시지를 출력하는것으로 보입니다.

**Comment by kmu-leeky** [comment]
오케이. 위의 운호 메시지를 놓쳤다. 에러 메시지는 잘 확인되었고, 이정도라면 괜찮을듯 하다.

**Comment by unhochoi** [comment]
3번 시나리오를 기반으로 container 를 생성해 Application 을 띄웠을 때도, 정상적으로 에러 처리하는 것을 확인했습니다.
<img width="1913" alt="image" src="https://user-images.githubusercontent.com/28581429/168789950-e38156fc-843b-486e-93dc-6af2be661805.png">

**Comment by kmu-leeky** [comment]
오케이. 수고했다.
다들 내일 실습 무리없이 진행되도록 실습 내용 잘 챙겨보도록 하자.
