### ISSUE TITLE
실습 당시, 일부 계정에서 CloudShell 접근이 안됐던 이유를 확인해야함

### ISSUE THREAD

**Issue by unhochoi** [ddps-lab/architect-cloud#6]

**Comment by unhochoi** [comment]
1-17 계정 정상 동작 확인 완료

**Comment by jaeriver** [comment]
35-51 계정 파악 완료
정상작동
- 35, 38, 39, 40, 51

에러발생
- 36, 37, 41-50

**Comment by hyoonseo159357** [comment]
18-34 계정 파악완료

32번 계정만 에러발생 / 나머지 계정은 모두 정상작동

**Comment by subeans** [comment]
52~68 계정 파악 완료 
+ 에러 발생 
52,53,54,55,56,57,58,60 ( cloudshell 접근 에러 )
61,62 ( get_sinin_link 생성 불가 에러 ) 

+ 정상 작동 
59 
63, 64 ,65 ,66 ,67 ,68 ( 단, user가 user00 형식으로 뜨지 않고 숫자로 표기됨 )

**Comment by unhochoi** [comment]
69~100번 계정을 확인해본 결과, 69~94번(26개) 계정이 정상작동하는 것을 확인했습니다.
나머지 95~100번 계정은 동작하지 않았습니다.
기존엔 23개의 계정이 사용 불가능 했기 때문에, 뒷쪽 계정으로 대체해서 사용할 수 있을 것 같긴합니다.

**Comment by subeans** [comment]
+ 52-68 계정 nuke 진행 이슈 
1. 53-60 에 대해서 nuke 작업 완료 ( 59 제외 cloudshell 불가능 )
2. 63-68 에 대해서 는 nuke 작업 불가능 , 따라서 직접 admin 삭제 , s3 삭제, config 역할 추가 진행
3. **link 자체가 생성안되는** 52, 61,62 에 대해서 추가로 부여받은 82, 83,84 계정으로 대체해서 마찬가지로 직접 초기화 진행
