### ISSUE TITLE
슬라이드 완성 후, Window 에서 Copy & Paste 를 확인해야함

### ISSUE THREAD

**Issue by unhochoi** [ddps-lab/architect-cloud#7]

**Comment by unhochoi** [comment]
1개의 텍스트 상자 내부에 여러 명령어가 적혀져있을 경우, Copy & Paste 가 어려웠음
여러 명령어가 필요하다면, 명령어를 라인별로 분리한 뒤, 라인 별로 텍스트 상자를 생성해야함
또한, 텍스트 상자는 겹쳐지면 안됨

**Comment by kmu-leeky** [comment]
아이고 복잡하다 ㅠㅠ 다른 쉬운 방법이 없으려나...

**Comment by kmu-leeky** [comment]
그런데 이문제는 작년에 해결했지 않았어? 작년 해결책이 저렇게 복잡했었나?

**Comment by unhochoi** [comment]
작년에 사용했던 해결 방법이 라인 별로 텍스트 박스를 분리하는 것이었습니다. 추가적인 해결 방법을 탐색해봐야할 것 같습니다.

**Comment by unhochoi** [comment]
3.CloudArchitectContainer-2022 확인 완료

**Comment by jaeriver** [comment]
4.CloudArchitectServerless-2022 
118번 슬라이드 복사부분 복붙이 어려움, README에 추가 완료

2.CloudArchitectHighAvailability-2022
복붙이 어려운 부분들 README에 추가 완료
