### ISSUE TITLE
pod 간 내부 통신 확인

### ISSUE THREAD

**Issue by mumat0103** [ddps-lab/architect-cloud#79]
3번 슬라이드 쿠버네티스 부분을 cloud shell로 최신화 하던 중, 에러가 발생했던 service 부분 pod 간 통신 부분의 명령어를 `curl` 에서 `wget`으로 변경하니 서버 응답을 확인할 수 있었습니다.
<img width="955" alt="스크린샷 2024-05-07 14 14 23" src="https://github.com/ddps-lab/architect-cloud/assets/69793985/8b07bb08-b43f-49f5-8737-b6b39a29d617">

**Comment by kmu-leeky** [comment]
이건 close 해도 되지?

**Comment by mumat0103** [comment]
네 완료했습니다. close 하겠습니다.
