### ISSUE TITLE
슬라이드 완성 후, 실습 계정 Nuke 및 Default VPC 생성

### ISSUE THREAD

**Issue by unhochoi** [ddps-lab/architect-cloud#8]

**Comment by unhochoi** [comment]
- 교수님, Nuke 시 aws-nuke-v2.15.0-darwin-amd64 파일이 필요한데, architect-cloud repo에 업로드해놓아도 괜찮을까요?
    - 기존에는 공식 Reference 에서 다운 받아 사용했었습니다.
- 또한, Nuke 시 삭제되지 않는 리소스들이 존재하는데, 모든 계정에 접속해 삭제하는게 좋을까요?
    - 예를 들어, 종속성이 있는 리소스, 내부 파일들이 존재하는 S3 버킷 등이 있습니다.

**Comment by kmu-leeky** [comment]
응 운호야. 누크 파일은 좋다. 
삭제 안되는것들은 굳이 수동으로하지는 말자. 시간이 너무 많이 들것 같고 그런 파일들로 실습을 못하는건 아니니까. 실습 다 마치고 깨끗하게 삭제해보자.

**Comment by unhochoi** [comment]
넵, 알겠습니다.

**Comment by subeans** [comment]
실습을 마치고 nuke 하는 작업을 진행하고 있습니다. 맡은 계정에 대해서 초기화를 진행하던 중, 일부 계정에서 Nuke가 불가능하여 이슈를 남깁니다. 
( 강의 전 Nuke가 안되는 계정에 대해서는 수동으로 접속하여 확인을 진행했었습니다. )
nuke 를 못하는 계정에서의 에러는 아래와 같습니다
Error: The specified account doesn't have an alias. For safety reasons you need to specify an account alias. Your production account should contain the term 'prod'.
계정에 접속 시 우측 상단의 cloud-architect-user00 로 account alias 가 있어야 하는데 계정ID 숫자로 뜨는 경우가 삭제가 진행되지 않습니다. 
이러한 계정은 제가 맡은 계정 기준으로 60번 후(61번부터)부터로 판단됩니다. 
이에 대한 해결 책으로 계정에 account alias 를 부여해야하는데 권한이 없어 진행하지 못하고 있습니다. 이에 대한 해결이 필요할 것 같습니다.

**Comment by kmu-leeky** [comment]
응 수빈아 잘 시도했다. 그런데 내가 전에 공유해준 account id  및 키에서 cli 를 활용하면 가능할거야. 

아래 코드를 보면 api 를 통해서 alias 를 생성하고 있거든. 전에 계정생성했던 곳에서 아래 코드를 적절히 활용하면 alias 를 적용 가능할거야. 한번 살펴보고 이슈 있으면 알려줘.

https://github.com/kmu-leeky/cloud-util/blob/master/create_account_link.py#L46

**Comment by unhochoi** [comment]
Nuke 완료 (0~17, 70~76, 92)

**Comment by subeans** [comment]
Nuke 완료 ( 53-60 , 63-68, 82,83,84 )

**Comment by hyoonseo159357** [comment]
Nuke 완료 (18-34 , 69)

**Comment by jaeriver** [comment]
Nuke 완료 (35-51, 93)
