### ISSUE TITLE
3번 슬라이드 Pod autoscaler로 Karpenter 사용

### ISSUE THREAD

**Issue by mumat0103** [ddps-lab/architect-cloud#80]

**Comment by mumat0103** [comment]
pod 오토스케일러로 Karpenter를 사용하는 시나리오를 적용합니다.

**Comment by kmu-leeky** [comment]
progress?

**Comment by mumat0103** [comment]
https://aws.amazon.com/ko/blogs/tech/amazon-eks-cluster-auto-scaling-karpenter-bp/

AWS 공식 블로그에서 설명을 잘 해놓은 것 같아 해당 글 보고 슬라이드 작업 진행하도록 하겠습니다.

**Comment by mumat0103** [comment]
카펜터 공식 문서 보면서 진행하고 있는데 에러가 발생하고 있어 시간이 좀 걸릴 것 같습니다. 주말 중으로 끝내보겠습니다.

**Comment by mumat0103** [comment]
카펜터 에러를 해결했습니다. 주말 중으로 PPT 제작하도록 하겠습니다.

**Comment by mumat0103** [comment]
카펜터를 사용하기 위해서 설정해야 할 부분이 많습니다. 그래서 기존에 클러스터 생성을 eksctl로 진행하던 것에서 콘솔에서 클러스터를 생성하는 것으로 변경하겠습니다.

**Comment by kmu-leeky** [comment]
성규야. 설정해야하는 부분이 어떤건지 이야기를 나눠보고 결정을 할까? 얼마나 더 복잡해지는지 궁금하기는 하다. 만약 수정되어야 하는게 많다면 다른 모듈에서 실습 내용의 영향 및 내용 중복등도 고려해봐야 할것 같아. 예를 들어 hpa 에서도 비슷한 실습을 하는것 같으니 내용의 중복이 있지 않을까 싶어서.

**Comment by mumat0103** [comment]
카펜터를 사용하기 위해서 addon을 클러스터에 추가해야 하고 IAM Role을 추가로 만들어야 합니다. 
추가로 카펜터를 위한 노드 그룹도 생성해주어야 합니다. 

eks 콘솔을 통해서 클러스터를 만들면 addon 설정이 기본값으로 설정되어 있어 추가로 작업을 해줄 필요가 없습니다.
CLI를 사용하는 것보다 콘솔을 통해서 생성하면 조금 더 직관적이라고 판단하여 해당 작업 진행하고 있었습니다.
hpa와 중복되는 내용은 딱히 없습니다.

**Comment by kmu-leeky** [comment]
오케이. 확인해봤는데 복잡해 보이기는 한다. hpa 와 중복이 되지 않는다면 카펜터로는 어떤 실습 내용이 추가되는거야?

**Comment by mumat0103** [comment]
HPA는 설정한 메트릭 수치 (예를 들면 CPU 사용량) 를 넘어가면 파드만 오토스케일링 하고 노드는 오토스케일링 하지 않는 것이고, 카펜터는 파드를 확장할 때 자원이 부족하면 추가로 노드까지 확장해주는 방법입니다. 
중복되는 부분이라면 파드 개수를 늘리고 줄이는 부분만 중복된다고 볼 수 있습니다.

**Comment by kmu-leeky** [comment]
응 그러네. 파드 개수 늘리는게 중복되기는 하겠다. 카펜터의 진도가 많이 나간것 같으니 한번 준비해보고 어떻게 배치할런지는 같이 이야기를 나눠보자.

**Comment by mumat0103** [comment]
카펜터 부분 초안 작성 완료하였습니다.

**Comment by mumat0103** [comment]
카펜터 부분 작성 완료하였습니다. 처음부터 검토하면서 추가할 내용 있으면 추가하도록 하겠습니다.

**Comment by kmu-leeky** [comment]
오케이 성규야 수고했다. 검토해보고 코멘트 줄께.

**Comment by mumat0103** [comment]
기존에 정리해놓은 이슈로 이동하겠습니다.
