### ISSUE TITLE
3번 슬라이드 ingress 설치 간단화 가능 여부 확인

### ISSUE THREAD

**Issue by mumat0103** [ddps-lab/architect-cloud#81]

**Comment by mumat0103** [comment]
3번 슬라이드에서 ingress를 사용하기 위해 helm을 사용하여 진행하는 부분이 있습니다. 해당 부분을 간단화가 가능한지 확인이 필요합니다.
@red0sena 경환님이 진행 부탁드립니다.

**Comment by kmu-leeky** [comment]
경환이 판단이 그렇다면 helm 으로 유지하자.

**Comment by red0sena** [comment]
helm으로 진행하기로 하였으므로 close하겠습니다
