### ISSUE TITLE
3번 슬라이드 pod 별 메모리, cpu 할당량 조절 하는 시나리오 추가

### ISSUE THREAD

**Issue by mumat0103** [ddps-lab/architect-cloud#83]

**Comment by mumat0103** [comment]
3번 슬라이드 116번 슬라이드 뒤에 pod 별 메모리, cpu 할당량을 조절하는 시나리오를 추가해야 합니다.
https://bcho.tistory.com/1291
@kh3654po 석현님이 해당 부분 진행 부탁드립니다.

**Comment by kh3654po** [comment]
추가하였습니다.

**Comment by kmu-leeky** [comment]
오케이. 잘했다. 슬라이드에 코멘트 남길께.

**Comment by kh3654po** [comment]
127~129 슬라이드에 추가되었으니 이 이슈는 클로즈하겠습니다.
