### ISSUE TITLE
3번 슬라이드 외부 접속 ingress 부분 오류 해결

### ISSUE THREAD

**Issue by mumat0103** [ddps-lab/architect-cloud#85]
3번 슬라이드 pod 외부 접속 ingress 부분에서 오류가 발생하고 있습니다.
슬라이드를 따라하면 커피 공급망 페이지에 접속할 수는 있으나, 경로가 맞지 않아 404에러가 발생합니다.
그리고 employee 페이지의 경우는 접근 자체가 불가능 합니다.
원인이 무엇인지 파악하고 수정하여 슬라이드에 반영해야 합니다.

![image](https://github.com/ddps-lab/architect-cloud/assets/69793985/dabc0cff-620c-4479-9f7b-5f3cbba638d7)

**Comment by red0sena** [comment]
<img width="1503" alt="image" src="https://github.com/ddps-lab/architect-cloud/assets/106056971/d9c33b3a-dd11-460a-96f9-5ddca2299895">
Customer이슈의 경우 클러스터 노드의 IP로 직접 접속하면 페이지가 잘 나타납니다. 

예상되는 원인으로는 coffee-ingress.yaml파일에서 path를 /customer로 잡고 있는데 이 부분이 실제 서비스 path에서는 없어서 404에러를 반환하는 것으로 보입니다.

https://github.com/ddps-lab/architect-cloud/blob/7cec4b8392d3064dcee3b7d1bba13811811838a5/2024/kubernetes/coffee-ingress.yaml#L11-L13


<img width="980" alt="Screenshot 2024-05-09 at 14 52 45" src="https://github.com/ddps-lab/architect-cloud/assets/106056971/3f56f8d7-7de5-4f2b-b6d3-dc33a9e1f01f">


해당경로를 수정해 보겠습니다.

**Comment by red0sena** [comment]
예상대로 /customer경로 문제였습니다. 
yaml파일의 path를 /으로 수정하니 정상적으로 customer페이지에 접근할 수 있었습니다.

<img width="1032" alt="image" src="https://github.com/ddps-lab/architect-cloud/assets/106056971/3d4d8a80-446a-4a6d-900a-24a90ed5a7cc">

추가적으로 employee에 접근할 수 없던 문제는 employee 포트 설정이 8081로 되어 있는데 yaml파일에서 8080포트에 매핑하여 발생한 문제로 보입니다. 해당 포트만 변경하면 될 것 같습니다.


추가적으로 현재 EKS에서 DB에 접근할 수 없는데 이는 VPC를 따로 설정하여 발생하는 문제입니다. 
EKS생성시 기존 subnet을 이용하게 하면 해결 가능할 것으로 보입니다.
<img width="950" alt="image" src="https://github.com/ddps-lab/architect-cloud/assets/106056971/493028a4-4217-471d-83a8-3d5d1034e076">

**Comment by mumat0103** [comment]
슬라이드 작업 제가 진행하도록 하겠습니다.

**Comment by mumat0103** [comment]
슬라이드 작업 완료하였습니다. Close 하겠습니다.
